site_name: GeoAI-Cookiecutter
site_description: A project template and directory structure for Python geograpihc data science projects.
site_favicon: favicon.ico
repo_url: https://github.com/ArcGIS/geoai-cookiecutter/
copyright: Esri Advanced Analytics Team
theme: cinder
extra_css:
  - css/extra.css
pages:
  - Home: index.md
